---
# argument spec file for oism.external_repo.gpg_keys

argument_specs:
  main:
    short_description: Role description.
    options:
      gpg_keys_my_variable:
        type: str
        description: A simple string argument for demonstration.
        default: "default_value"
